### ISSUE TITLE
Cannot see top right corner buttons

### ISSUE THREAD

**Issue by GeoffreyDlvl** [Remi-Guijarro/ENSIIE_OOP_Inventory#1]
Maybe because I'm not under windows and my computer has no knowledge of the smileys that are used ? Maybe we should consider another way to display these icons.

**Comment by Remi-Guijarro** [comment]
I changed emoticons by images, hope this will hansure portability amongs all OS

**Comment by GeoffreyDlvl** [comment]
Apparently resolved by a51968ac8a0feea771f508359a96e887dd53ca78
